### ISSUE TITLE
startup race condition on joint positions

### ISSUE THREAD

**Issue by suddrey-qut** [qcr/armer#14]
If a latched pose goal is received before the first joint state message is registered with the robot then the following error is generated

`
[ERROR] [1636937448.492012]: Exception in your execute callback: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 0 is different from 7)
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/robot/armer_ws/src/armer/armer/robots/ROSRobot.py", line 372, in pose_cb
    if self.__traj_move(traj, goal.speed if goal.speed else 0.2):
  File "/home/robot/armer_ws/src/armer/armer/robots/ROSRobot.py", line 677, in __traj_move
    current_twist = jacob0 @ current_jv
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 0 is different from 7)
`

**Comment by suddrey-qut** [comment]
Fixed
